@startuml
    folder "src" as src_b874d07 {
      rectangle "index.ts" as index_ts_e4daf83f {
      }
      folder "util" as util_28bcbc6c {
        object "errors" as errors_90641da1 {
        }
        object "logger" as logger_d1ee5f1e {
        }
        class "SomeClass" as some_class_3e48ea5d {
        }
        interface "SomeInterface" as some_interface_7947f676 {
        }
        
      }
    }
  index_ts_e4daf83f -up-> some_class_3e48ea5d
  index_ts_e4daf83f -up-> logger_d1ee5f1e
  
  
  
  
@enduml