@startuml
    folder "src" as src_b874d07 {
      artifact "index.ts" as index_ts_e4daf83f {
      }
      folder "util" as util_28bcbc6c {
        abstract "AbstractClass" as abstract_class_48ddc9a9 {
          + {abstract} test(someParam: string): number
        }
        object "errors" as errors_90641da1 {
          + throwError(msg: string): void
        }
        object "logger" as logger_d1ee5f1e {
          + debug(msg: string): void
        }
        interface "OtherInterface" as other_interface_9bbef566 {
          + test: number
        }
        card "T: SomeType" as some_type_3e48ea5d {
        }
        class "SomeClass" as some_class_3e48ea5d {
          # _constParam: string
          # _constParam1: string
          + constructor(params: { test: string; test1: SomeType })
          + test: number
        }
        enum "SomeEnumType" as some_enum_type_688a0b15 {
          FIRST_VALUE = 'first-value'
          SECOND_VALUE = 'second-value'
          THIRD_VALUE = 'third-value'
        }
        interface "SomeInterface" as some_interface_7947f676 {
          + test: number
        }
      }
    }
  index_ts_e4daf83f -up-> some_class_3e48ea5d
  index_ts_e4daf83f -up-> logger_d1ee5f1e
  logger_d1ee5f1e -up-> errors_90641da1
  some_class_3e48ea5d -up-> errors_90641da1
  some_class_3e48ea5d -up-|> abstract_class_48ddc9a9
  some_class_3e48ea5d .up.|> some_interface_7947f676
  some_class_3e48ea5d .up.|> other_interface_9bbef566
@enduml