@startuml
    folder "src" as src_b874d07 {
      artifact "index.ts" as index_ts_e4daf83f {
      }
      folder "enum" as enum_1eea471b {
        enum "LoggerType" as logger_type_eca21c7c {
          INFO = 'info'
          WARN = 'warn'
        }
        enum "SomeEnumType" as some_enum_type_6a1c7ee2 {
          FIRST_VALUE = 'first-value'
          SECOND_VALUE = 'second-value'
          THIRD_VALUE = 'third-value'
        }
      }
      folder "service" as service_c83a6ab5 {
        abstract "AbstractClass" as abstract_class_eb5b4d10 {
          + {abstract} test(someParam: string): number
        }
        interface "OtherInterface" as other_interface_45739bff {
          + test: number
        }
        card some_type_755b9f64 [
          SomeType
          ---
          string
        ]
        card some_other_type_755b9f64 [
          SomeOtherType
          ---
          {
            test: string
            flag: boolean
            obj: {
              test1: true
              test2: true
            }
          }
        ]
        class "SomeClass" as some_class_755b9f64 {
          # _constParam: string
          # _constParam1: string
          + constructor(params: {\n test: string;\n test1: SomeType \n})
          + test(someParam: string): number
          + test: number
          + test(someParam?: string): number
          + test1: SomeEnumType
        }
        interface "SomeInterface" as some_interface_4140baef {
          + test: number
        }
        folder "folder/subfolder" as folder_subfolder_85d5d271 {
          object "nested" as nested_27b6e15a {
            + someFunction: Promise<void>
          }
        }
      }
      folder "util" as util_28bcbc6c {
        object "errors" as errors_90641da1 {
          + throwError(msg: string): void
        }
        object "logger" as logger_d1ee5f1e {
          + debug(msg: string): void
        }
      }
    }
  index_ts_e4daf83f -up-> some_class_755b9f64
  index_ts_e4daf83f -up-> logger_d1ee5f1e
  some_class_755b9f64 -up-> errors_90641da1
  some_class_755b9f64 -up-> some_enum_type_6a1c7ee2
  some_class_755b9f64 -up-> path_6f8e1be1
  some_class_755b9f64 -up-> some_type_755b9f64
  some_class_755b9f64 -up-|> abstract_class_eb5b4d10
  some_class_755b9f64 .up.|> some_interface_4140baef
  some_class_755b9f64 .up.|> other_interface_45739bff
  logger_d1ee5f1e -up-> errors_90641da1
  logger_d1ee5f1e -up-> logger_type_eca21c7c
@enduml