@startuml
    rectangle "index.ts" as index_ts_6269cc92 {
    }
    folder "app" as app_a8039b31 {
      class "CliApp" as cli_app_6c2f2528 {
      }
      object "app" as app_e4dabcfc {
      }
      folder "init" as init_61709104 {
        class "ExecArgsAsCommand" as exec_args_as_command_f1e47953 {
        }
        
      }
    }
    folder "dal" as dal_407cd159 {
      object "shellDal" as shell_dal_fd4c3230 {
      }
      
    }
    folder "enum" as enum_6eb1a43 {
      rectangle "puml-group-type.ts" as puml_group_type_ts_bf4cc633 {
      }
      rectangle "reference-type.ts" as reference_type_ts_8da7d56e {
      }
      
    }
    folder "model" as model_f99a517f {
      class "EntityClass" as entity_class_a46bc114 {
      }
      class "EntityEnum" as entity_enum_7a751249 {
      }
      class "EntityFile" as entity_file_b7c4115c {
      }
      class "EntityInterface" as entity_interface_fbd810df {
      }
      class "EntityObject" as entity_object_726f13cf {
      }
      class "EntityType" as entity_type_95fb9502 {
      }
      class "Entity" as entity_91a0e537 {
      }
      interface "Exportable" as exportable_86d3462 {
      }
      interface "Locatable" as locatable_ca77b0f3 {
      }
      interface "Referencable" as referencable_536a5808 {
      }
      class "Reference" as reference_484c2c07 {
      }
      
    }
    folder "module" as module_66df848a {
      rectangle "ts.ts" as ts_ts_e991f5e {
      }
      
    }
    folder "service" as service_c15a056d {
      object "argsService" as args_service_9de50b29 {
      }
      object "cliService" as cli_service_78084628 {
      }
      object "fileService" as file_service_31964988 {
      }
      object "helpService" as help_service_eb5e7b3f {
      }
      object "shellService" as shell_service_f120d930 {
      }
      folder "command" as command_e61b1f05 {
        interface "Executable" as executable_52d7d0c6 {
        }
        class "Generate" as generate_2344c2dd {
        }
        class "PrintHelp" as print_help_8cbc7a1b {
        }
        class "PrintVersion" as print_version_14ba8d30 {
        }
        
      }
      folder "convert" as convert_d463a275 {
        object "convertService" as convert_service_3ce98fc1 {
        }
        interface "ConvertStrategy" as convert_strategy_f6692c87 {
        }
        folder "ts" as ts_3f50c77d {
          class "TsConvert" as ts_convert_cbb8a473 {
          }
          class "TsEntityParser" as ts_entity_parser_7c9a08b5 {
          }
          object "self" as self_d27817cf {
          }
          object "tsEntityService" as ts_entity_service_d27817cf {
          }
          object "tsParserService" as ts_parser_service_f934a93 {
          }
          folder "parser" as parser_ab04d355 {
            interface "Parsable" as parsable_fa92107c {
            }
            class "TsParserClass" as ts_parser_class_5262a4e8 {
            }
            class "TsParserFile" as ts_parser_file_d83fca0 {
            }
            class "TsParserImport" as ts_parser_import_303bb93b {
            }
            class "TsParserInterface" as ts_parser_interface_93e54043 {
            }
            class "TsParserObject" as ts_parser_object_d264a153 {
            }
            class "TsParserType" as ts_parser_type_9c7333be {
            }
            
          }
        }
      }
      folder "print" as print_cc10bc53 {
        interface "PrintStrategy" as print_strategy_5ec3c47 {
        }
        folder "puml" as puml_17686618 {
          class "PumlDocument" as puml_document_bb3b71cd {
          }
          class "PumlEntity" as puml_entity_c1aa58b9 {
          }
          class "PumlGroup" as puml_group_7884f7fd {
          }
          class "PumlPrint" as puml_print_3457d353 {
          }
          class "PumlRelation" as puml_relation_58f69104 {
          }
          folder "printable-entity" as printable_entity_10c203fa {
            class "PumlPrintableClass" as puml_printable_class_68644af8 {
            }
            class "PumlPrintableFile" as puml_printable_file_7ebc32b0 {
            }
            class "PumlPrintableInterface" as puml_printable_interface_583c8a73 {
            }
            class "PumlPrintableObject" as puml_printable_object_2f522563 {
            }
            class "PumlPrintableWrapper" as puml_printable_wrapper_4574fc85 {
            }
            
          }
        }
      }
    }
    folder "use-case" as use_case_fabd4e2a {
      object "cliInitUseCase" as cli_init_use_case_e074087f {
      }
      object "visionUseCase" as vision_use_case_e3840bea {
      }
      
    }
    folder "util" as util_24c07134 {
      object "env" as env_36b4f26d {
      }
      object "config" as config_36b4f26d {
      }
      object "packageJson" as package_json_e60a4099 {
      }
      object "constant" as constant_e60a4099 {
      }
      object "logger" as logger_15d2abb3 {
      }
      object "shortHash" as short_hash_6730c0db {
      }
      object "self" as self_6730c0db {
      }
      object "stringUtil" as string_util_6730c0db {
      }
      
    }
  
  
  
  
  
  
  index_ts_6269cc92 -up-> logger_d1ee5f1e
  
  
  
  
  
  
  
  
  
  
  
  ts_ts_e991f5e -up-> ts_71c661ae
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
@enduml