@startuml
  rectangle "application" as application_97208b5f {
    rectangle "index.ts" as index_ts_6269cc92 {
    }
    folder "app" as app_b8770c4 {
      class "CliApp" as cli_app_6c2f2528 {
      }
      object "app" as app_e4dabcfc {
      }
      folder "init" as init_32171df1 {
        class "ExecArgsAsCommand" as exec_args_as_command_f1e47953 {
        }
        
      }
    }
    folder "dal" as dal_b873fec {
      object "ExecResult" as exec_result_fd4c3230 {
      }
      object "shellDal" as shell_dal_fd4c3230 {
      }
      
    }
    folder "model" as model_a58ed8a {
      class "Entity" as entity_91a0e537 {
      }
      class "ImportReference" as import_reference_30d19bd7 {
      }
      
    }
    folder "module" as module_45878c7f {
      rectangle "ts.ts" as ts_ts_e991f5e {
      }
      
    }
    folder "service" as service_e5e0e198 {
      object "ArgsServiceParams" as args_service_params_9de50b29 {
      }
      object "CliCommands" as cli_commands_9de50b29 {
      }
      object "CmdGenerateParams" as cmd_generate_params_9de50b29 {
      }
      object "argsService" as args_service_9de50b29 {
      }
      object "cliService" as cli_service_78084628 {
      }
      object "fileService" as file_service_31964988 {
      }
      object "helpService" as help_service_eb5e7b3f {
      }
      object "PrintStdMessage" as print_std_message_f120d930 {
      }
      object "shellService" as shell_service_f120d930 {
      }
      folder "command" as command_2a794330 {
        rectangle "executable.ts" as executable_ts_52d7d0c6 {
        }
        class "Generate" as generate_2344c2dd {
        }
        class "PrintHelp" as print_help_8cbc7a1b {
        }
        class "PrintVersion" as print_version_14ba8d30 {
        }
        
      }
      folder "convert" as convert_12278480 {
        object "convertService" as convert_service_3ce98fc1 {
        }
        rectangle "convert-strategy.ts" as convert_strategy_ts_f6692c87 {
        }
        folder "ts" as ts_2a1b2388 {
          class "TsConvert" as ts_convert_cbb8a473 {
          }
          object "self" as self_d27817cf {
          }
          object "tsEntityService" as ts_entity_service_d27817cf {
          }
          object "tsService" as ts_service_325486d9 {
          }
          folder "statement-entity" as statement_entity_1f7d3a74 {
            object "tsStatementEntityService" as ts_statement_entity_service_6f09511b {
            }
            object "TsMetaObject" as ts_meta_object_8f050d6b {
            }
            object "TsMetaClass" as ts_meta_class_8f050d6b {
            }
            object "TsMetaImport" as ts_meta_import_8f050d6b {
            }
            object "TsMetaType" as ts_meta_type_8f050d6b {
            }
            object "TsMetaEnum" as ts_meta_enum_8f050d6b {
            }
            object "TsMeta" as ts_meta_8f050d6b {
            }
            object "TsStatementEntity" as ts_statement_entity_8f050d6b {
            }
            rectangle "ts-statement-entity.ts" as ts_statement_entity_ts_8f050d6b {
            }
            folder "parser" as parser_65a3181c {
              object "tsParserClass" as ts_parser_class_64f52814 {
              }
              object "tsParserImport" as ts_parser_import_a071ab67 {
              }
              object "tsParserObject" as ts_parser_object_70ee294f {
              }
              object "tsParserService" as ts_parser_service_1365a407 {
              }
              object "tsParserType" as ts_parser_type_11d02802 {
              }
              
            }
          }
        }
        folder "typescript-parser" as typescript_parser_98e20b52 {
          object "importExtractor" as import_extractor_e95fa6b4 {
          }
          class "TypescriptParserConvert" as typescript_parser_convert_c7090573 {
          }
          object "typescriptParserEntityService" as typescript_parser_entity_service_fa9124cf {
          }
          
        }
      }
      folder "print" as print_22892ee6 {
        rectangle "print-strategy.ts" as print_strategy_ts_5ec3c47 {
        }
        class "Printable" as printable_9580899b {
        }
        folder "puml" as puml_a8f74ced {
          class "PumlPrint" as puml_print_3457d353 {
          }
          class "PumlTemplate" as puml_template_f0711fd2 {
          }
          folder "group" as group_78ebcdbd {
            object "pumlGroupService" as puml_group_service_17932e5d {
            }
            class "PumlGroup" as puml_group_b48e88ad {
            }
            
          }
          folder "printable-entity" as printable_entity_2c7e384f {
            class "PumlPrintableClass" as puml_printable_class_68644af8 {
            }
            object "pumlPrintableEntityService" as puml_printable_entity_service_a873edfd {
            }
            class "PumlPrintableFile" as puml_printable_file_7ebc32b0 {
            }
            class "PumlPrintableObject" as puml_printable_object_2f522563 {
            }
            
          }
          folder "relation" as relation_1f6d2ac4 {
            object "pumlRelationService" as puml_relation_service_3d5a51bd {
            }
            class "PumlRelation" as puml_relation_51da0e0d {
            }
            
          }
        }
      }
    }
    folder "use-case" as use_case_5dae941f {
      object "cliInitUseCase" as cli_init_use_case_e074087f {
      }
      object "visionUseCase" as vision_use_case_e3840bea {
      }
      
    }
    folder "util" as util_7c6f1d01 {
      object "config" as config_36b4f26d {
      }
      object "constant" as constant_e60a4099 {
      }
      object "logger" as logger_15d2abb3 {
      }
      object "stringUtil" as string_util_6730c0db {
      }
      
    }
  }
  exec_args_as_command_f1e47953 -up-> cli_init_use_case_e074087f
  generate_2344c2dd -up-> puml_print_3457d353
  puml_printable_class_68644af8 -up-> printable_9580899b
  puml_printable_file_7ebc32b0 -up-> printable_9580899b
  puml_printable_object_2f522563 -up-> printable_9580899b
@enduml