@startuml
  folder app {
    object "index" as index_6269cc92 {
    }
    folder util {
      object "errors" as errors_9c0c198c {
      }
      object "logger" as logger_15d2abb3 {
      }
      object "neka-klasa" as neka_klasa_5b3f669f {
      }
    
    }
  }
  
  index_6269cc92 --> logger_15d2abb3
  
@enduml