@startuml
    rectangle "index.ts" as index_ts_6269cc92 {
    }
    folder "util" as util_24c07134 {
      object "errors" as errors_9c0c198c {
      }
      object "logger" as logger_15d2abb3 {
      }
      class "SomeClass" as some_class_7f27bf30 {
      }
      interface "SomeInterface" as some_interface_d80ef49b {
      }
      
    }
@enduml